# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [3]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
#shape выводит кортеж, в котором указаны размеры измерений
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[1.51689320e-03 4.76978674e-01 2.86368758e-01 ... 9.35123444e-01
  3.15398993e-02 7.95283217e-01]
 [7.11697000e-01 5.82009753e-04 7.90796388e-01 ... 5.77832046e-02
  7.47033819e-01 4.17380720e-02]
 [9.50625719e-01 3.44412246e-02 5.76873230e-01 ... 7.82609356e-01
  8.96212363e-01 2.01850048e-01]
 ...
 [4.70862981e-01 7.82746901e-01 3.59754196e-01 ... 6.35439493e-01
  4.33050586e-01 7.89596578e-01]
 [8.34414413e-01 4.00373364e-01 2.54888951e-01 ... 8.11720485e-01
  6.06776600e-01 5.92400316e-01]
 [7.59655421e-01 4.72824265e-01 5.57480846e-01 ... 3.33463583e-01
  8.07161746e-01 1.36701697e-01]]
[[0.99988274 0.86016799 0.71688592 ... 0.92974145 0.83217944 0.97237223]
 [0.64157438 0.36231567 0.05364087 ... 0.96702896 0.35963604 0.99428904]
 [0.09246496 0.52387088 0.95425686 ... 0.9656161  0.37512635 0.82016593]
 ...
 [0.41126889 0.88536166 0.8140879  ... 0.39975155 0.62574186 0.01795824]
 [0.38164676 0.6959

Без использования numpy

In [ ]:
def mult(a, b):
    length = len(a)
    result = [[0 for i in range(length)] for i in range(length)]
    for i in range(length):
      for j in range(length):
        for k in range(length):
          result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [ ]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 718 ms, sys: 0 ns, total: 718 ms
Wall time: 724 ms


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.29 ms, sys: 0 ns, total: 1.29 ms
Wall time: 2.63 ms


In [ ]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.4711787343912874e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.23065565 0.68577026 0.2180858 ] [0.17298977 0.9136115  0.77291371]


In [ ]:
def scalar_product(a,b):
    return sum(x * y for x, y in zip(a, b))

In [ ]:
def np_scalar_product(a,b):
    return np.dot(a, b)

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 27 µs, sys: 5 µs, total: 32 µs
Wall time: 35.8 µs
CPU times: user 48 µs, sys: 0 ns, total: 48 µs
Wall time: 50.8 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Во втором случае мой метод оказался чуть быстрее, думаю это из-за маленького объема данных. Numpy использует язык C для вычисления математических операций, также он используют оптимизированые алгоритмы. Numpy обеспечивает высокую скорость, не типичную обычному python, время выполнения в первом случае оказывалась в несколько сотен раз меньше, чем без numpy.


------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    diagonal_elements = np.diag(a)
    even_elements = diagonal_elements[diagonal_elements % 2 == 0]
    result = np.sum(even_elements) if len(even_elements) > 0 else 0

    return result

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[9, 8, 1, 2, 1],
       [3, 6, 6, 7, 3],
       [1, 6, 9, 1, 4],
       [9, 3, 2, 6, 6],
       [6, 8, 8, 3, 3]])

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 137 µs, sys: 21 µs, total: 158 µs
Wall time: 163 µs


12

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [9]:
def np_sec_av(X):
    return np.cumsum(X)

In [11]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[3.76193346e-01 3.66840750e-01 2.45033200e-01 8.94956594e-01
 4.79365719e-01 4.18106857e-01 8.38801591e-01 1.93265872e-01
 9.26963126e-01 3.02510080e-01 2.28835811e-01 8.21351562e-01
 4.84289945e-01 9.82484133e-01 5.50507569e-01 2.47725569e-01
 2.98880360e-01 5.54316902e-02 4.90019523e-01 1.57091315e-01
 5.86713738e-01 8.60585468e-01 8.63951281e-01 1.23038560e-01
 3.47150950e-01 1.28062152e-01 1.68971985e-02 6.43587951e-01
 9.94286546e-01 3.08742265e-02 6.00984208e-02 6.41213762e-01
 4.45115113e-01 1.02342506e-01 8.68980932e-01 7.80911846e-01
 5.05833762e-01 3.85212755e-01 2.37897272e-01 9.53484907e-01
 6.54451265e-01 2.70966791e-01 6.21572279e-01 9.05743228e-01
 5.23983506e-01 8.79329858e-01 1.97904934e-01 4.80133924e-01
 7.21641996e-01 3.24563715e-01 3.25587472e-01 4.22956349e-01
 4.17436926e-01 2.90336960e-01 5.06742356e-01 5.16199090e-02
 8.98499904e-01 6.95826380e-01 8.83673946e-01 8.29732524e-01
 9.28498914e-01 9.93841067e-01 9.92925790e-01 1.90989867e-01
 5.07012677e-01 6.029970

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [25]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    if len(a) == 0:
        return np.array([]), np.array([])
    change_indices = np.where(a[:-1] != a[1:])[0]
    num = np.diff(np.concatenate(([-1], change_indices, [len(a)-1])))
    x = a[change_indices]

    return x, num

In [26]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
print(num)

CPU times: user 154 µs, sys: 0 ns, total: 154 µs
Wall time: 160 µs
[1 2 2 2 2 1 2]


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [36]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    result = np.copy(X)
    result[1::2] = a
    result[::2] **= 3
    result = np.flip(result)
    result = np.concatenate((X, result))

    return result

In [40]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)
print(S2)

CPU times: user 122 µs, sys: 0 ns, total: 122 µs
Wall time: 129 µs
[  1   3   5   7   9 729   5 125   5   1]
[1 3 5 7 9]
